=== hmcts/pcq-backend/src/test/resources/JsonSchema/submitAnswersSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "classpath:/JsonSchema/answer_definitions_schema.json",
  "type": "object",
  "title": "The PCQ Response Schema",
  "required": [
    "pcqId",
    "partyId",
    "channel",
    "completedDate",
    "serviceId",
    "actor",
    "versionNo",
    "pcqAnswers"
  ],
  "properties": {
    "pcqId": {
      "id": "#pcqId",
      "type": "string",
      "title": "The PCQ Identifier"
    },
    "ccdCaseId": {
      "id": "#ccdCaseId",
      "type": ["string", "null"],
      "title": "The Case Identifier"
    },
    "partyId": {
      "id": "#partyId",
      "type": "string",
      "title": "The Party Identifier"
    },
    "channel": {
      "id": "#channel",
      "type": "integer",
      "title": "The Channel of ingress",
      "default": 1,
      "enum": [ 1, 2 ]
    },
    "completedDate": {
      "id": "#completedDate",
      "type": "string",
      "title": "The Completed Date",
      "pattern": "\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d(?:\\.\\d+)?Z?"
    },
    "serviceId": {
      "id": "#serviceId",
      "type": "string",
      "title": "The Service Identifier"
    },
    "actor": {
      "id": "#actor",
      "type": "string",
      "title": "The Actor"
    },
    "versionNo": {
      "id": "#versionNo",
      "type": "integer",
      "title": "The Version Number"
    },
    "optOut": {
      "id": "#optOut",
      "type": ["string", "null"],
      "title": "The Opt Out Flag",
      "enum": ["Y", null]
    },
    "pcqAnswers": {
      "id": "#pcqAnswers",
      "title": "The PCQ Answers",
      "$ref": "#/definitions/all_answers"
    }
  }
}

=== hmcts/pcq-backend/src/functionalTest/resources/JsonTestFiles/InvalidVersion.json
{
  "pcqId": "T1234",
  "ccdCaseId": null,
  "partyId": "23",
  "channel": 1,
  "completedDate": "2020-03-05T09:13:45",
  "serviceId": "PROBATE_TEST",
  "actor": "DEFENDANT",
  "versionNo": 2,
  "pcqAnswers": {
    "dob_provided": 1,
    "dob": "1970-01-01T00:00:00.000Z",
    "language_main": null
  }
}

=== hmcts/pcq-backend/src/integrationTest/resources/JsonTestFiles/Pregnancy.json
{
  "pcqId": "UPDATE-INTEG-TEST",
  "ccdCaseId": "CCD-Case-2",
  "partyId": "23",
  "channel": 1,
  "completedDate": "2020-03-05T09:13:46.000Z",
  "serviceId": "PROBATE",
  "actor": "RESPONDENT",
  "versionNo": 1,
  "pcqAnswers": {
    "dob_provided": 1,
    "dob": "1985-01-01T00:00:00.000Z",
    "language_main": 0,
    "language_other": "TestLanguage",
    "english_language_level": 3,
    "sex": null,
    "gender_different": 2,
    "gender_other": "TestGender",
    "sexuality": 4,
    "sexuality_other": "OtherSexuality",
    "marriage": 1,
    "ethnicity": 18,
    "ethnicity_other": "TestOtherEthnicity",
    "religion": 8,
    "religion_other": "TestOtherReligion",
    "disability_conditions": 1,
    "disability_impact": 0,
    "disability_vision": 0,
    "disability_hearing": 1,
    "disability_mobility": null,
    "disability_dexterity": 0,
    "disability_learning": 1,
    "disability_memory": 1,
    "disability_mental_health": 0,
    "disability_stamina": 0,
    "disability_social": 1,
    "disability_other": 1,
    "disability_other_details": "Other test disabilities",
    "disability_none": 0,
    "pregnancy": 2
  }
}

=== hmcts/pcq-backend/src/test/resources/JsonTestFiles/MainLanguageEnglishOrWelsh.json
{
  "pcqId": "T1234",
  "ccdCaseId": null,
  "partyId": "23",
  "channel": 1,
  "completedDate": "2020-03-05T09:13:45.000Z",
  "serviceId": "PROBATE",
  "actor": "DEFENDANT",
  "versionNo": 1,
  "pcqAnswers": {
    "dob_provided": 1,
    "dob": "1970-01-01T00:00:00.000Z",
    "language_main": 1
  }
}

=== hmcts/pcq-backend/src/integrationTest/resources/JsonTestFiles/UpdateMainLanguageEnglishOrWelsh.json
{
  "pcqId": "UPDATE-INTEG-TEST",
  "ccdCaseId": "CCD-Case-2",
  "partyId": "23",
  "channel": 1,
  "completedDate": "2020-03-05T09:13:46.000Z",
  "serviceId": "PROBATE",
  "actor": "RESPONDENT",
  "versionNo": 1,
  "pcqAnswers": {
    "dob_provided": 1,
    "dob": "1985-01-01T00:00:00.000Z",
    "language_main": 1
  }
}

=== hmcts/pcq-backend/src/functionalTest/resources/JsonTestFiles/UpdateSubmitAnswer.json
{
  "pcqId": "UPDATE-FUNC-TEST",
  "ccdCaseId": null,
  "partyId": "test@test2.com",
  "channel": 1,
  "completedDate": "2020-03-05T09:13:46.000Z",
  "serviceId": "PROBATE_TEST",
  "actor": "DEFENDANT",
  "versionNo": 1,
  "pcqAnswers": {
    "dob_provided": 1,
    "dob": "1985-01-01T00:00:00.000Z",
    "language_main": 0,
    "language_other": "TestLanguage",
    "english_language_level": 3,
    "sex": 1,
    "gender_different": 2,
    "gender_other": "TestGender",
    "sexuality": 4,
    "sexuality_other": "OtherSexuality",
    "marriage": 1,
    "ethnicity": 18,
    "ethnicity_other": "TestOtherEthnicity",
    "religion": 8,
    "religion_other": "TestOtherReligion",
    "disability_conditions": 1,
    "disability_impact": 0,
    "disability_vision": 0,
    "disability_hearing": 1,
    "disability_mobility": null,
    "disability_dexterity": 0,
    "disability_learning": 1,
    "disability_memory": 1,
    "disability_mental_health": 0,
    "disability_stamina": 0,
    "disability_social": 1,
    "disability_other": 1,
    "disability_other_details": "Other test disabilities",
    "disability_none": 0,
    "pregnancy": 2
  }
}
